'use server';

/**
 * @fileOverview An AI flow for generating a complete affiliate website.
 *
 * - generateWebsite - A function that generates content for a homepage and legal pages.
 * - GenerateWebsiteInput - The input type for the generateWebsite function.
 * - GenerateWebsiteOutput - The return type for the generateWebsite function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { websiteThemes } from '@/lib/data';


const GenerateWebsiteInputSchema = z.object({
  username: z.string().describe("The affiliate's username, used to construct their referral link."),
  themeName: z.string().optional().describe("The name of the color theme for the website."),
});
export type GenerateWebsiteInput = z.infer<typeof GenerateWebsiteInputSchema>;

// Schema for the content generated by the LLM
const WebsiteContentSchema = z.object({
  homepage: z.object({
    title: z.string().describe('A creative and SEO-friendly title for the website.'),
    
    navLinks: z.array(z.object({
        text: z.string().describe('Navigation link text.'),
        href: z.string().describe('The anchor link for the section (e.g., #features).')
    })).length(3).describe('A list of 3 navigation links for the header.'),

    headline: z.string().describe('The main, catchy headline for the hero section of the homepage.'),
    subheadline: z.string().describe('A short, persuasive subheadline that supports the main headline.'),
    ctaButtonText: z.string().describe('Compelling text for the primary call-to-action button in the hero section.'),

    featuresHeadline: z.string().describe('A headline for the features section.'),
    features: z.array(z.object({
      title: z.string().describe('The title of a key feature.'),
      description: z.string().describe('A brief description of the feature.'),
      icon: z.string().describe('A simple, single emoji to represent the feature (e.g., \'🚀\').')
    })).length(3).describe('A list of exactly 3 key features of the Affiliate AI Host platform.'),

    howItWorksHeadline: z.string().describe('A headline for the "How it Works" section.'),
    howItWorksSteps: z.array(z.object({
        title: z.string().describe('The title of a step in the process.'),
        description: z.string().describe('A brief description of the step.'),
    })).length(3).describe('A list of exactly 3 steps explaining how the affiliate process works.'),
    
    testimonialsHeadline: z.string().describe('A headline for the testimonials section.'),
    testimonials: z.array(z.object({
        text: z.string().describe('The text of the testimonial.'),
        name: z.string().describe('The fictional name of the person giving the testimonial.'),
        role: z.string().describe('The fictional role of the person (e.g., Blogger, Entrepreneur).')
    })).length(3).describe('A list of exactly 3 fictional testimonials.'),

    faqHeadline: z.string().describe('A headline for the FAQ section.'),
    faqs: z.array(z.object({
        question: z.string().describe('A frequently asked question.'),
        answer: z.string().describe('The answer to the question.')
    })).min(3).max(5).describe('A list of 3 to 5 frequently asked questions.'),
    
    finalCtaHeadline: z.string().describe('A headline for the final call-to-action section.'),
    finalCtaSubheadline: z.string().describe('A subheadline for the final call-to-action section.'),
    finalCtaButtonText: z.string().describe('Text for the final call-to-action button.'),
  }),
  terms: z.string().describe('The full text for a generic Terms of Service page suitable for an affiliate site.'),
  privacy: z.string().describe('The full text for a generic Privacy Policy page suitable for an affiliate site.'),
  disclaimer: z.string().describe('The full text for a generic Earnings Disclaimer page suitable for an affiliate site.'),
});

// Schema for the final output of the flow, including the theme
const ColorThemeSchema = z.object({
  '--primary-color': z.string(),
  '--secondary-color': z.string(),
  '--background-color': z.string(),
  '--card-background': z.string(),
  '--text-color': z.string(),
  '--muted-color': z.string(),
});

const GenerateWebsiteOutputSchema = WebsiteContentSchema.extend({
  username: z.string(),
  theme: z.object({
    name: z.string(),
    colors: ColorThemeSchema,
  }),
  error: z.string().optional(),
  retryAfter: z.number().optional(),
});
export type GenerateWebsiteOutput = z.infer<typeof GenerateWebsiteOutputSchema>;


export async function generateWebsite(input: GenerateWebsiteInput): Promise<GenerateWebsiteOutput> {
  return websiteGeneratorFlow(input);
}

const prompt = ai.definePrompt({
    name: 'websiteGeneratorPrompt',
    input: { schema: z.object({ username: z.string() }) }, // Prompt only needs username
    output: { schema: WebsiteContentSchema }, // The LLM only generates the content
    prompt: `You are an expert copywriter and web designer specializing in high-converting affiliate marketing websites.

Your task is to generate the complete text content for a professional, multi-section, single-page affiliate website. The website's sole purpose is to promote "Affiliate AI Host", a platform that offers AI-powered web hosting and a lucrative affiliate program with daily payouts.

The affiliate's username is "{{username}}". All call-to-action links on the site will point to their unique referral link: https://hostproai.com/?ref={{username}}.

The tone should be enthusiastic, trustworthy, and benefit-oriented. Generate content that is creative and persuasive. Critically, you must vary the wording and angle for each generation to ensure the websites are unique, but always maintain the core goal of getting visitors to click the affiliate link.

Generate content for the following pages, formatted as a single JSON object:

1.  **Homepage**: This is the main landing page. It should be comprehensive and compelling, similar to a full-featured professional landing page.
    *   **title**: A creative, SEO-friendly title for the website (e.g., "Your Daily Income Engine" or "The AI-Powered Affiliate Shortcut").
    *   **navLinks**: A list of 3 navigation links for the header. The text should be short (e.g., 'Features', 'How it Works', 'FAQ') and the href should be an anchor link (e.g., '#features').
    *   **headline**: A powerful, attention-grabbing headline for the hero section.
    *   **subheadline**: A concise subheadline that explains the main benefit.
    *   **ctaButtonText**: Action-oriented text for the main call-to-action button in the hero section.
    *   **featuresHeadline**: A headline for the features section (e.g., "Why Partner with Affiliate AI Host?").
    *   **features**: A list of exactly 3 key features of Affiliate AI Host. For each, provide a catchy title, a brief benefit-focused description, and a single, relevant emoji. Examples: "Daily PayPal Payouts", "Generous 70% Commissions (Scale to 75%)", "Built-in AI Content Tools".
    *   **howItWorksHeadline**: A headline for the "How it Works" section (e.g., "Your Simple Path to Daily Income").
    *   **howItWorksSteps**: A list of exactly 3 simple steps explaining the process: 1. Sign up, 2. Promote, 3. Get Paid Daily.
    *   **testimonialsHeadline**: A headline for the testimonials section (e.g., "Trusted by Top Earners").
    *   **testimonials**: A list of exactly 3 fictional but realistic and persuasive testimonials from different types of users (e.g., a blogger, a marketer, a side-hustler).
    *   **faqHeadline**: A headline for the FAQ section (e.g., "Frequently Asked Questions").
    *   **faqs**: A list of 3-5 common questions and answers about the affiliate program.
    *   **finalCtaHeadline**: A headline for the final, bottom-of-page call-to-action section.
    *   **finalCtaSubheadline**: A brief, urgent subheadline for the final CTA.
    *   **finalCtaButtonText**: A strong, action-oriented button text for the final CTA.
    
2.  **Legal Pages**: Generate standard, generic boilerplate text for the following legal pages. The content should be suitable for a small, independent affiliate marketing website.
    *   **terms**: A simple Terms of Service.
    *   **privacy**: A simple Privacy Policy.
    *   **disclaimer**: A simple Earnings Disclaimer, making it clear that earnings are not guaranteed.

Do not include any markdown formatting like \`\`\`json in your output. The output must be a pure JSON object that strictly adheres to the provided schema.`,
});

// This is a dummy object that satisfies the schema constraints, used for returning on error.
const dummyHomepage = {
    title: 'Error',
    navLinks: [{text:'',href:''},{text:'',href:''},{text:'',href:''}],
    headline: 'Error',
    subheadline: 'An error occurred during generation.',
    ctaButtonText: 'Try Again',
    featuresHeadline: 'Error',
    features: [{title:'',description:'',icon:''},{title:'',description:'',icon:''},{title:'',description:'',icon:''}],
    howItWorksHeadline: 'Error',
    howItWorksSteps: [{title:'',description:''},{title:'',description:''},{title:'',description:''}],
    testimonialsHeadline: 'Error',
    testimonials: [{text:'',name:'',role:''},{text:'',name:'',role:''},{text:'',name:'',role:''}],
    faqHeadline: 'Error',
    faqs: [{question:'',answer:''},{question:'',answer:''},{question:'',answer:''}],
    finalCtaHeadline: 'Error',
    finalCtaSubheadline: 'Please try again later.',
    finalCtaButtonText: 'Error',
};


const websiteGeneratorFlow = ai.defineFlow(
    {
        name: 'websiteGeneratorFlow',
        inputSchema: GenerateWebsiteInputSchema,
        outputSchema: GenerateWebsiteOutputSchema,
    },
    async (input): Promise<GenerateWebsiteOutput> => {
        const theme = websiteThemes.find(t => t.name === input.themeName) || websiteThemes[Math.floor(Math.random() * websiteThemes.length)];
        
        try {
            const { output } = await prompt({ username: input.username });
            if (!output) {
                return {
                    homepage: dummyHomepage,
                    terms: 'Error generating content.',
                    privacy: 'Error generating content.',
                    disclaimer: 'Error generating content.',
                    theme: theme,
                    username: input.username,
                    error: 'The AI model did not return any content.'
                };
            }
            return { ...output, username: input.username, theme: theme };
        } catch (e: any) {
            console.error('Website Generation Error:', e);
            const rawErrorMessage = e.message || 'An unknown error occurred.';
            
            let userFriendlyError = `The connection to the AI service failed. This could be a network issue or a problem with your Google Cloud project setup. Please check your environment and configuration. Raw error: "${rawErrorMessage}"`;
            let retrySeconds: number | undefined = undefined;

            if (rawErrorMessage.includes("API key not valid")) {
                userFriendlyError = `Authentication failed. The Gemini API Key you provided in the .env file appears to be invalid. Please double-check that you have copied the entire key correctly. If you just updated the key, you may need to restart the development server. Raw error: "${rawErrorMessage}"`;
            } else if (rawErrorMessage.includes("Quota exceeded") || rawErrorMessage.includes("Too Many Requests") || rawErrorMessage.includes("billing account not found")) {
                 userFriendlyError = `Action Required: To use your account's credits, you must enable the 'Generative Language API' for this project. Even if billing is active, this specific API needs to be turned on. It's a quick, one-time step. Please use the button that now appears on the screen to enable the API, then try again in a moment. Raw error: "${rawErrorMessage}"`;
                 const match = rawErrorMessage.match(/Please retry in ([\d.]+)s/);
                 if (match && match[1]) {
                     retrySeconds = Math.ceil(parseFloat(match[1]));
                 }
            }

            return {
                homepage: dummyHomepage,
                terms: 'Error generating content.',
                privacy: 'Error generating content.',
                disclaimer: 'Error generating content.',
                theme: theme,
                username: input.username,
                error: userFriendlyError,
                retryAfter: retrySeconds,
            };
        }
    }
);